CREATE TABLE ITEM (ID BIGINT NOT NULL, DESCRIPTION VARCHAR, PRICE DOUBLE, TITLE VARCHAR, PRIMARY KEY (ID))
CREATE TABLE BOOK (ID BIGINT NOT NULL, AUTHOR VARCHAR, CATEGORY VARCHAR, DESCRIPTION VARCHAR, EDITORIAL VARCHAR, IMAGE VARCHAR, ISBN VARCHAR, LANGUAGE VARCHAR, PAGES INTEGER, PRICE INTEGER, STOCK INTEGER, TITLE VARCHAR, YEAR INTEGER, PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
