CREATE TABLE ITEM (ID BIGINT NOT NULL, DESCRIPTION VARCHAR, PRICE DOUBLE, TITLE VARCHAR, PRIMARY KEY (ID))
CREATE TABLE CLIENTE (ID BIGINT NOT NULL, IDENTIFICACION VARCHAR, CIUDAD VARCHAR, CODIGO_POSTAL VARCHAR, DIRECCION VARCHAR, ESTADO VARCHAR, FECHA_ALTA TIMESTAMP, FECHA_BAJA TIMESTAMP, PAIS VARCHAR, TIPO_CLIENTE VARCHAR, PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
